### ISSUE TITLE
iCOR integration

### ISSUE THREAD

**Issue by jarekdobrzanski** [parameterspace-ie/eo4a-service-trials#21]
We're getting a following error. I presume this has to do with the way paths are being passed between linked services in processing chain:

```
            Process error: EO4AProcess.py._run_process Line 384 task: non-zero exit (1)
Installing dependencies for iCOR service
Finishing file write...
Installing iCOR plugin...
Copying iCOR files into the installation folder : /opt/vito/icor
Done
iCOR installation for SNAP finished
Traceback (most recent call last):
  File "/opt/eo4a/service/icor/wrapper.py", line 65, in <module>
    main()
  File "/opt/eo4a/service/icor/wrapper.py", line 39, in main
    extract_files(input_dir)
  File "/opt/eo4a/service/icor/wrapper.py", line 12, in extract_files
    for item in os.listdir(dir_name):
OSError: [Errno 2] No such file or directory: 'resource-management.data:scihub/output/scihub'
```

**Comment by derekocallaghan** [comment]
`wrapper.py` changes the current working directory with the call to `os.chdir(dir_name)`. This should be removed, the current working directory should never be changed as any relative paths (e.g. `resource-management`) will no longer be accessible.

**Comment by jarekdobrzanski** [comment]
This is removed in the latest provided commit

**Comment by derekocallaghan** [comment]
Closing as this issue was resolved.
