### ISSUE TITLE
iCOR and Matchups integration - write permissions problem

### ISSUE THREAD

**Issue by jarekdobrzanski** [parameterspace-ie/eo4a-service-trials#22]
What would be the best way around the problem as per error below? I was following your [sentinel processing shellscripts](https://github.com/parameterspace-ie/eo4a-service-development/blob/master/sentinel/sentinel2ndvi) that seem to suggest (unzip ect.) that write operation on output directory from previous processing step is possible.

```
             Process error: EO4AProcess.py._run_process Line 384 task: non-zero exit (1)
> /opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
>   warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
> Parsing arguments...
> ['/opt/eo4a/service/matchups/wrapper.py', '--in_situ_data', '2018-01-25T10:10:00,0.45,2018-02-06T09:58:00,1.03,2018-02-08T10:47:00,2.34', '--time_tolerance', '1200', '--match_radius', '0.005', '--input_dir', 'resource-management.coda/output/coda', '--user_api_key', 'api_key_1015', '--longitude', '3.35', '--username', 'jdobrzanski', '--workflow_id', 'f97061b5-8165-41f0-85a3-95a46b1742e3', '--latitude', '52.68', '--parameter', 'chl_nn', '--user_session', 'None', 'twm.matchups/output']
> Extracting  S3A_OL_2_WFR____20180109T102750_20180109T103050_20180110T162237_0179_026_279_2159_MAR_O_NT_002.SEN3.zip
> Traceback (most recent call last):
>   File "/opt/eo4a/service/matchups/wrapper.py", line 183, in <module>
>     main()
>   File "/opt/eo4a/service/matchups/wrapper.py", line 130, in main
>     extract_files(args.input_dir)
>   File "/opt/eo4a/service/matchups/wrapper.py", line 27, in extract_files
>     zip_ref.extractall(dir_name)
>   File "/opt/conda/lib/python2.7/zipfile.py", line 1043, in extractall
>     self.extract(zipinfo, path, pwd)
>   File "/opt/conda/lib/python2.7/zipfile.py", line 1031, in extract
>     return self._extract_member(member, path, pwd)
>   File "/opt/conda/lib/python2.7/zipfile.py", line 1082, in _extract_member
>     os.mkdir(targetpath)
> OSError: [Errno 30] Read-only file system: 'resource-management.coda/output/coda/S3A_OL_2_WFR____20180109T102750_20180109T103050_20180110T162237_0179_026_279_2159_MAR_O_NT_002.SEN3'
```
```

**Comment by derekocallaghan** [comment]
The current service will only have read-only access to the output directories of previous services, and will have read-write access to its own output directory (`self.output_dir` in `wps.py`). The product zip files should be extracted somewhere in `self.output_dir`.

Separately, the user should not be specifying the output file as a WPS input. Instead, `self.output_dir` should be used to set the value of the corresponding WPS output directory parameter. See this service for an example: https://github.com/parameterspace-ie/eo4a-service-development/blob/master/sentinel/wps.py

**Comment by derekocallaghan** [comment]
Closing as this issue was resolved.
